Assert all jobs succeeded

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -4,10 +4,6 @@ on:
   workflow_dispatch:
 
 jobs:
-  test-actions:
-    uses: ./.github/workflows/test-actions.yml
-    secrets: inherit
-
   test-scripts:
     runs-on: ubuntu-latest
     steps:
@@ -16,3 +12,32 @@ jobs:
 
       - name: Test scripts
         run: ./test_scripts.sh
+
+  test-get-hz-versions:
+    uses: ./.github/workflows/test-get-hz-versions.yml
+
+  test-slack-notification:
+    uses: ./.github/workflows/test-slack-notification.yml
+    secrets: inherit
+
+  test-get-supported-jdks:
+    uses: ./.github/workflows/test-get-supported-jdks.yml
+
+  assert-all-jobs-succeeded:
+    runs-on: ubuntu-latest
+    needs:
+      - test-scripts
+      - test-get-hz-versions
+      - test-slack-notification
+      - test-get-supported-jdks
+    if: always()
+    steps:
+      - name: Check all jobs succeeded
+        run: |
+          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "❌ Some jobs failed or were cancelled"
+            exit 1
+          else
+            echo "✅ All jobs completed successfully!"
+          fi
+
